signer = "0x117be1de549d1d4322c4711f11efa0c5137903124f85fc37c761ffc91ace30cb"
share = "0x006b170a6a737021ce871c154f6681ea2297b65bfcce6eb2e6a43c5e8a40fefba4"
polynomial = "0x98c6e82fdf8990fa8b78df3788c45d4a36d83dd6c4e619b7b746abe12891427dd93ccd2d00596b8a87a5b084578fd2cf0a1f3a02672f4b370b2601e6425f873eafeb10a62adaa093b503a8630b89994c5f1401e62001896d2bd4f858be2cb94186445b36c1e706cf466b003845b0aabdade971bd12eae6c97c5c489d77b55301fc0c20d3c70172c9e80441cf1c1168680906ac1638aa86671fb3e5cecbc9356b30044ca8e8cc1b3baa4389d62fba2812e1d3820f63f7785f763f82fb3b3cf1a787f4417a797c779941dc3a61fe17cf23ea885f447cd319aed4ebe916242968f781480c2c06980ec7c1b6b6c73f0b51cf04f301e6bd7d10b45e2106510af7bff7ee392f4319224352722fd1cd5c1d1f2785caf6808be769232813fd78804397b7"
listen_port = 8000
metrics_port = 8001
storage_directory = "/tmp/consensus"
worker_threads = 3
bootstrappers = [
  "0x2a685998ee44953a3eb0a5d316937f810a80bdcc952c0aa07b4d82b3fed459c2",
]
message_backlog = 16384
mailbox_size = 16384
deque_size = 10
fee_recipient = "0x0000000000000000000000000000000000000000"

[p2p]
max_message_size_bytes = 1048576

[peers]
0x0c229e27a8c69e7afe86900dfbceab6ef6d207582c127a0d99fe9b3fb5a2068a = "tempo-validator-0:8000"
0x2a685998ee44953a3eb0a5d316937f810a80bdcc952c0aa07b4d82b3fed459c2 = "tempo-validator-1:8000"
0x7f7fdd1ca8d7c3ed8206137178b47bcafe7a54d4a0b4ce5bd9e25978184b48ce = "tempo-validator-2:8000"
0xee1aa49a4459dfe813a3cf6eb882041230c7b2558469de81f87c9bf23bf10a03 = "tempo-validator-3:8000"

[timeouts]
time_for_peer_response = "200ms"
time_to_collect_notarizations = "200ms"
time_to_propose = "200ms"
time_to_retry_nullify_broadcast = "3s"
views_to_track = 256
views_until_leader_skip = 32
new_payload_wait_time = "100ms"
