name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check code
        run: pnpm check

      - name: Check types
        run: pnpm preconstruct && pnpm check:types

  test-local:
    name: 'Test Runtime (tag: ${{ matrix.tag }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: 
          - latest
          - https://rpc.testnet.tempo.xyz
          - https://devnet.tempoxyz.dev

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Setup Docker
        uses: docker/setup-docker-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_DOCKER_PAT }}

      - name: Cache Playwright
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-1.56.1

      - name: Install Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpx playwright@1.56.1 install --with-deps

      - name: Run tests
        run: pnpm test --bail=1
        env:
          CI: true

  test-deployed:
    name: Test Runtime (e2e) (${{ matrix.rpc-env }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rpc-env: 
          - devnet
          # - testnet
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run tests
        run: pnpm test e2e --bail=1
        env:
          CI: true
          VITE_NODE_ENV: ${{ matrix.rpc-env }}