name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check code
        run: pnpm check

      - name: Check build
        run: pnpm build

      - name: Check types
        run: pnpm check:types

  test-localnet:
    name: 'Test Runtime (env: localnet, tag: ${{ matrix.tag }})'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        tag: 
          - latest
          - https://rpc.testnet.tempo.xyz

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Setup Docker
        uses: docker/setup-docker-action@v4

      - name: Run tests
        run: pnpm test --bail=1
        env:
          CI: true
          VITE_NODE_TAG: ${{ matrix.tag }}
          VITE_RPC_CREDENTIALS: ${{ secrets.VITE_RPC_CREDENTIALS }}
